hardly_check = false
per_gov_check = false
tcp_bbr3_check = true
cachy_config_check = true
nconfig_check = false
xconfig_check = false
localmodcfg_check = true
use_current_check = false
builtin_zfs_check = false
builtin_nvidia_open_check = false
build_debug_check = false
hz_ticks_combo = "500"
tickrate_combo = "idle"
preempt_combo = "full"
hugepage_combo = "madvise"
lto_combo = "thin"
cpu_opt_combo = "native"
custom_name_edit = "$pkgbase-mine"
