"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

format = """
[░▒▓](#a3aed2)\
$os\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[os]
style = "bg:#a3aed2 fg:#090c0c"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
CachyOS = "󰣇"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#66ccc3"
red       = "#fd4663"
green     = "#6794e4"
yellow    = "#8172ee"
cyan      = "#a296e9"
magenta   = "#93b3ec"
white     = "#f2f2f3"
black     = "#1e2534"

# Extended palette (Catppuccin-compatible names)
rosewater = "#8172ee"
flamingo  = "#fd4663"
pink      = "#93b3ec"
mauve     = "#93b3ec"
maroon    = "#fd4663"
peach     = "#8172ee"
teal      = "#a296e9"
sky       = "#a296e9"
sapphire  = "#66ccc3"
lavender  = "#93b3ec"

# Text shades
text      = "#f2f2f3"
subtext1  = "#f2f2f3"
subtext0  = "#626771"

# Surface shades
overlay2  = "#626771"
overlay1  = "#626771"
overlay0  = "#1e2534"
surface2  = "#1e2534"
surface1  = "#1e2534"
surface0  = "#161c27"
base      = "#161c27"
mantle    = "#161c27"
crust     = "#161c27"
# <<< NOCTALIA STARSHIP PALETTE <<<
