search_mode = "daemon-fuzzy"
inline_height = 0
scroll_exits = false
show_preview = true


[ai]
enabled = true
endpoint = "http://127.0.0.1:8080"
endpoint_protocol = "oss"
model_name = "mimo-v2.5"


[daemon]
enabled = true
autostart = true


[dotfiles]
enabled = true


[sync]
records = true
sync_address = "http://127.0.0.1:8080" 
auto_sync = true
