# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000918"

# Main text color
theme[main_fg]="#35daff"

# Title color for boxes
theme[title]="#fa1bf8"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7640ff"

# Background color of selected item in processes box
theme[selected_bg]="#35daff"

# Foreground color of selected item in processes box
theme[selected_fg]="#000918"

# Color of inactive/disabled text
theme[inactive_fg]="#7640ff"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#fa1bf8"

# Background color of the percentage meters
theme[meter_bg]="#35daff"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#fa1bf8"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#35daff" #Blue
theme[mem_box]="#35daff" #Blue
theme[net_box]="#35daff" #Blue
theme[proc_box]="#35daff" #Blue

# Box divider line and small boxes line color
theme[div_line]="#35daff"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#35daff"
theme[temp_mid]="#7640ff"
theme[temp_end]="#fa1bf8"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#35daff"
theme[cpu_mid]="#7640ff"
theme[cpu_end]="#fa1bf8"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#35daff"
theme[free_mid]="#7640ff"
theme[free_end]="#fa1bf8"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#35daff"
theme[cached_mid]="#7640ff"
theme[cached_end]="#fa1bf8"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#35daff"
theme[available_mid]="#7640ff"
theme[available_end]="#fa1bf8"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#35daff"
theme[used_mid]="#7640ff"
theme[used_end]="#fa1bf8"

# Download graph colors (Peach -> Red)
theme[download_start]="#35daff"
theme[download_mid]="#7640ff"
theme[download_end]="#fa1bf8"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#35daff"
theme[upload_mid]="#7640ff"
theme[upload_end]="#fa1bf8"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#35daff"
theme[process_mid]="#7640ff"
theme[process_end]="#fa1bf8"
